"""Doctor style indexer — NS5.

For each validated SOAP consultation, computes a quality_score by measuring
the cosine similarity between the generated SOAP embedding and the validated
SOAP embedding. If quality_score > 0.7 the validated SOAP is chunked, embedded,
and stored as DoctorStyleChunk rows for use as few-shot examples in future prompts.

The quality_score is also persisted on the Consultation row and as a
ValidationMetric record.

Usage:
    from ia.rag.indexer.doctor_style_indexer import DoctorStyleIndexer

    indexer = DoctorStyleIndexer(db)
    result = await indexer.index_validated_soap(
        consultation_id=uuid4,
        soap_generated={"soap": {...}},
        soap_validated={"soap": {...}},
        medecin_id=uuid4,
        motif_key="fièvre",      # normalised motif for retrieval grouping
    )
    if result is not None:
        print(f"Indexed {len(result)} style chunks (score={result[0].quality_score})")
"""
from __future__ import annotations

import json
import logging
import re
import uuid
from dataclasses import dataclass
from typing import Optional

from sqlalchemy.ext.asyncio import AsyncSession

log = logging.getLogger(__name__)

# Minimum quality score to store as style example
_MIN_QUALITY_SCORE = 0.7

# Chunk size for style examples (smaller than RAG chunks to keep few-shots concise)
_STYLE_CHUNK_CHARS = 1200
_STYLE_OVERLAP_CHARS = 150


@dataclass
class StyleChunkResult:
    chunk_id: uuid.UUID
    medecin_id: uuid.UUID
    text: str
    quality_score: float
    motif_key: str


class DoctorStyleIndexer:
    """Async indexer for NS5 DoctorStyleChunk rows.

    Args:
        db: AsyncSession with RLS context set for this doctor's cabinet.
    """

    def __init__(self, db: AsyncSession) -> None:
        self._db = db

    async def index_validated_soap(
        self,
        *,
        consultation_id: uuid.UUID,
        soap_generated: dict,
        soap_validated: dict,
        medecin_id: uuid.UUID,
        motif_key: str = "",
    ) -> Optional[list[StyleChunkResult]]:
        """Index validated SOAP as style examples if quality_score > 0.7.

        Args:
            consultation_id:  UUID of the Consultation row.
            soap_generated:   Raw SOAP dict as generated by Claude.
            soap_validated:   Final SOAP dict after doctor edits.
            medecin_id:       UUID of the validating doctor.
            motif_key:        Normalised motif (e.g. "fievre", "hta") for retrieval.

        Returns:
            List of StyleChunkResult if stored, or None if quality_score ≤ 0.7.
        """
        # Embed both SOAPs on-premise to compute quality_score
        gen_text = _soap_to_text(soap_generated)
        val_text = _soap_to_text(soap_validated)

        gen_vec, val_vec = await _embed_async([gen_text, val_text])
        quality_score = _cosine_similarity(gen_vec, val_vec)

        log.info(
            "[DoctorStyleIndexer] consultation=%s quality_score=%.3f",
            consultation_id, quality_score,
        )

        # Persist quality_score on the Consultation + ValidationMetric
        await self._persist_metrics(consultation_id, medecin_id, quality_score)

        if quality_score <= _MIN_QUALITY_SCORE:
            log.info(
                "[DoctorStyleIndexer] score %.3f ≤ %.1f — not indexing style",
                quality_score, _MIN_QUALITY_SCORE,
            )
            return None

        # Chunk + embed the validated SOAP text
        chunks = _chunk_text(val_text)
        embeddings = await _embed_async(chunks)

        results: list[StyleChunkResult] = []
        for idx, (chunk_text, vec) in enumerate(zip(chunks, embeddings)):
            chunk_id = await self._upsert_style_chunk(
                medecin_id=medecin_id,
                text=chunk_text,
                embedding=vec,
                chunk_index=idx,
                metadata={
                    "consultation_id": str(consultation_id),
                    "quality_score": quality_score,
                    "motif_key": _normalise_motif(motif_key),
                },
            )
            results.append(StyleChunkResult(
                chunk_id=chunk_id,
                medecin_id=medecin_id,
                text=chunk_text,
                quality_score=quality_score,
                motif_key=_normalise_motif(motif_key),
            ))

        log.info(
            "[DoctorStyleIndexer] Stored %d style chunks for consultation %s",
            len(results), consultation_id,
        )
        return results

    async def _upsert_style_chunk(
        self,
        *,
        medecin_id: uuid.UUID,
        text: str,
        embedding: list[float],
        chunk_index: int,
        metadata: dict,
    ) -> uuid.UUID:
        from sqlalchemy import text as sa_text
        import json as _json

        chunk_id = uuid.uuid4()
        stmt = sa_text(
            """
            INSERT INTO doctor_style_chunk
                (id, medecin_id, text, embedding, chunk_index, created_at)
            VALUES
                (:id, :medecin_id, :text, CAST(:embedding AS vector), :chunk_index, NOW())
            """
        )
        await self._db.execute(stmt, {
            "id": str(chunk_id),
            "medecin_id": str(medecin_id),
            "text": text,
            "embedding": str(embedding),
            "chunk_index": chunk_index,
        })
        await self._db.commit()
        return chunk_id

    async def _persist_metrics(
        self,
        consultation_id: uuid.UUID,
        medecin_id: uuid.UUID,
        quality_score: float,
    ) -> None:
        from sqlalchemy import text as sa_text

        # Update quality_score on the Consultation row
        await self._db.execute(
            sa_text(
                "UPDATE consultation SET quality_score = :qs WHERE id = :cid"
            ),
            {"qs": quality_score, "cid": str(consultation_id)},
        )

        # Insert ValidationMetric
        await self._db.execute(
            sa_text(
                """
                INSERT INTO validation_metric (id, consultation_id, medecin_id, quality_score, created_at)
                VALUES (uuid_generate_v4(), :cid, :mid, :qs, NOW())
                ON CONFLICT DO NOTHING
                """
            ),
            {
                "cid": str(consultation_id),
                "mid": str(medecin_id),
                "qs": quality_score,
            },
        )
        await self._db.commit()


# ── Helpers ───────────────────────────────────────────────────────────────────

def _soap_to_text(soap_dict: dict) -> str:
    """Flatten a SOAP dict to a single string for embedding."""
    soap = soap_dict.get("soap", soap_dict)
    parts: list[str] = []

    for key in ("S", "O", "A", "P"):
        section = soap.get(key)
        if isinstance(section, dict):
            parts.append(f"[{key}] " + json.dumps(section, ensure_ascii=False))
        elif isinstance(section, str) and section.strip():
            parts.append(f"[{key}] {section}")

    return " ".join(parts)


def _chunk_text(text: str) -> list[str]:
    """Split text into style-sized chunks."""
    if len(text) <= _STYLE_CHUNK_CHARS:
        return [text.strip()]

    sentences = re.split(r"(?<=[.!?])\s+", text)
    chunks: list[str] = []
    current_parts: list[str] = []
    current_len = 0

    for sentence in sentences:
        s_len = len(sentence)
        if current_len + s_len > _STYLE_CHUNK_CHARS and current_parts:
            chunk = " ".join(current_parts).strip()
            if chunk:
                chunks.append(chunk)
            overlap = chunk[-_STYLE_OVERLAP_CHARS:]
            current_parts = [overlap]
            current_len = len(overlap)

        current_parts.append(sentence)
        current_len += s_len + 1

    if current_parts:
        last = " ".join(current_parts).strip()
        if last:
            chunks.append(last)

    return chunks


def _normalise_motif(motif: str) -> str:
    """Lowercase, strip accents, strip punctuation for consistent key matching."""
    import unicodedata
    nfkd = unicodedata.normalize("NFKD", motif.lower().strip())
    ascii_str = "".join(c for c in nfkd if not unicodedata.combining(c))
    return re.sub(r"[^a-z0-9\s]", "", ascii_str).strip()


def _cosine_similarity(a: list[float], b: list[float]) -> float:
    """Compute cosine similarity between two vectors."""
    import math
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(x * x for x in b))
    if norm_a == 0.0 or norm_b == 0.0:
        return 0.0
    return dot / (norm_a * norm_b)


async def _embed_async(texts: list[str]) -> list[list[float]]:
    """Embed texts on-premise using CamemBERT-bio."""
    import asyncio
    from ia.embedding.service import get_embedding_service

    loop = asyncio.get_event_loop()
    service = get_embedding_service()

    def _embed_sync():
        return service.embed(texts)

    vectors = await loop.run_in_executor(None, _embed_sync)
    return [v.tolist() if hasattr(v, "tolist") else list(v) for v in vectors]
